# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    gcc \
    g++ \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Install virtualenv
RUN pip install --upgrade pip && pip install virtualenv

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Create a virtual environment and install dependencies
RUN virtualenv myenv
RUN dos2unix myenv/bin/activate
RUN . myenv/bin/activate && pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app/

# Expose the port Flask is running on
EXPOSE 5000

# Command to activate virtualenv and run the app
CMD ["/bin/bash", "-c", "source myenv/bin/activate && python app.py"]
